alias pgstart="pg_ctl -D $PREFIX/var/lib/postgresql start"
alias pgstop="pg_ctl -D $PREFIX/var/lib/postgresql stop"
#alias soft="~/go/bin/soft"
alias ls="ls -Fla"
alias gp="git pull && git push"
alias grep="rg"
